# Generated by Django 2.2 on 2021-08-12 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('j_schatz_app', '0005_codechallenge'),
    ]

    operations = [
        migrations.RenameField(
            model_name='codechallenge',
            old_name='creator',
            new_name='publisher',
        ),
    ]
