# Generated by Django 2.2 on 2021-08-12 04:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('j_schatz_app', '0006_auto_20210811_2045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codechallenge',
            name='publisher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenges', to='login_app.User'),
        ),
    ]
