# Generated by Django 2.2 on 2021-10-02 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('j_schatz_app', '0007_auto_20210811_2118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codechallenge',
            name='publisher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codechallenges', to='login_app.User'),
        ),
    ]
